#!/usr/bin/env bash
################################################################################
#
#   # #   # #  ###  #####     #####  ###   ###  #     ###
#   # ##  # # #       #         #   #   # #   # #    #
#   # # # # #  ###    #   ###   #   #   # #   # #     ### 
#   # #  ## #     #   #         #   #   # #   # #        #
#   # #   # #  ###    #         #    ###   ###  ##### ###
#
# Lanceur des outils « inist-tools »
#
# @author : INIST-CNRS/DPI
#
################################################################################

#-------------------------------------------------------------------------------
# Environnement
#-------------------------------------------------------------------------------
MODULE_NAME="INIST-TOOLS"
CURDIR=$( cd "$( dirname "$0" )" && pwd )
DIR_MODULE=$(readlink -f "$CURDIR")
DIR_CONF="$DIR_MODULE/conf"
DIR_LIBS="$DIR_MODULE/libs"
DIR_TOOLS="$DIR_MODULE/tools"
DIR_INSTALL="$DIR_MODULE/install"
MODULE_VERSION=$(cd "$DIR_MODULE" && git describe --tags)
MODULE_VERSION_SHORT=$(cd "$DIR_MODULE" && git describe --tags | cut -d"-" -f1)


#-------------------------------------------------------------------------------
# Chargement libs + conf
#-------------------------------------------------------------------------------
if [ -f "$DIR_LIBS/std.rc" ]; then
  # source "$DIR_LIBS/ansicolors.lib.sh"
  source "$DIR_LIBS/std.rc"
else
  logger -s "[$MODULE_NAME] [ERROR] Impossible de charger la librairie de $MODULE_NAME depuis « $DIR_LIBS ». Fin."
  exit 1
fi

if [ -f "$DIR_CONF/inist.conf.sh" ]; then
  source "$DIR_CONF/inist.conf.sh"
else
  logger -s "[$MODULE_NAME] [ERROR] Impossible de charger la configuration de $MODULE_NAME depuis « $DIR_LIBS ». Fin."
  exit 1
fi

#-------------------------------------------------------------------------------
# Vérification des dépendances
#-------------------------------------------------------------------------------
if ! _it_std_check_command "find" ; then
  _it_std_message "ERROR" "« find » non trouvé, veuillez l'installer avant de continuer."
  exit 1
fi

#-------------------------------------------------------------------------------
# Gestion des arguments 
#-------------------------------------------------------------------------------

# Aucun argument : affichage de l'aide
if [ "$#" -lt 1 ]; then
  _it_std_greeting
  _it_std_message "WARNING" "Nombre d'argument incorrect !"
  _it_std_show_help
  exit 0
fi

#-------------------------------------------------------------------------------
# COMMANDE [+option[s]]
#-------------------------------------------------------------------------------
# On est poli, on dit bonjour...
_it_std_greeting

# ...et on traite la ligne de commande
case $1 in

  #---------------------------------------------------------------------------
  # COMMANDE : info
  #---------------------------------------------------------------------------
  info )
    # On charge la lib "network"
    source "$DIR_LIBS/network.lib.sh"
    #
    _it_network_info
  ;;

  #---------------------------------------------------------------------------
  # COMMANDE : proxy
  #---------------------------------------------------------------------------
  proxy )
    
    case "$2" in
      
      #-----------------------------------------------------------------------
      # inist proxy on
      #-----------------------------------------------------------------------
      on )

        case "$3" in
          # inist proxy on --firefox (ou --iceweasel)
          --firefox|iceweasel )
          ;;
          
          # inist proxy off --chrome (ou --chromium)
          --chrome|chromium )
          ;;
          # Cas par défaut (application à tout le système)
          *)
            _it_std_message "INFO" "Positionnement des variables d'environnement pour le proxy INIST"
            source "$DIR_LIBS/inist-proxy.rc"
            _it_inistProxy_on
          ;;
        esac
      ;;
      
      #-----------------------------------------------------------------------
      # inist proxy off
      #-----------------------------------------------------------------------
      off )

        case "$3" in
          # inist proxy off --firefox (ou --iceweasel)
          --firefox|iceweasel )
          ;;
          
          # inist proxy off --chrome (ou --chromium)
          --chrome|chromium )
          ;;
          # Cas par défaut (application à tout le système)
          *)
            _it_std_message "INFO" "Suppression des variables d'environnement pour le proxy INIST"
            source "$DIR_LIBS/inist-proxy.rc"
            _it_inistProxy_off
          ;;
        esac
      ;;
      
      #-----------------------------------------------------------------------
      # inist proxy (sans sous-commande)
      #-----------------------------------------------------------------------
      * )
        _it_std_message "INFO" "Positionnement des variables d'environnement pour le proxy INIST"
        source "$DIR_TOOLS/proxy-on.rc"
      ;;
      
    esac
  ;;

  #---------------------------------------------------------------------------
  # OPTION : --version
  #---------------------------------------------------------------------------
  --version | -v )
    cat "$DIR_LIBS/gfx/cnrs.ansi"
    _it_std_show_version
    exit 0
  ;;

  #---------------------------------------------------------------------------
  # Options non gérées...
  #---------------------------------------------------------------------------

  * )
    _it_std_show_help
  ;;
  
esac


#-------------------------------------------------------------------------------
# Fin (propre)
#-------------------------------------------------------------------------------
exit 0
