#!/usr/bin/env bash
########################################################################
#
#   # #   # #  ###  #####     #####  ###   ###  #     ###
#   # ##  # # #       #         #   #   # #   # #    #
#   # # # # #  ###    #   ###   #   #   # #   # #     ### 
#   # #  ## #     #   #         #   #   # #   # #        #
#   # #   # #  ###    #         #    ###   ###  ##### ###
#
# Lanceur des outils « inist-tools »
#
# @author : INIST-CNRS/DPI
#
########################################################################

#-----------------------------------------------------------------------
# Environnement
#-----------------------------------------------------------------------
MODULE_NAME="INIST-TOOLS"
MODULE_VERSION=$(git describe --tags)
MODULE_VERSION_SHORT=$(git describe --tags | cut -d"-" -f1 )
CURDIR=$( cd "$( dirname "$0" )" && pwd )
DIR_MODULE=$(readlink -f "$CURDIR")
DIR_CONF="$DIR_MODULE/conf"
DIR_LIBS="$DIR_MODULE/libs"
DIR_TOOLS="$DIR_MODULE/tools"

#-----------------------------------------------------------------------
# Chargement libs + conf
#-----------------------------------------------------------------------
if [ -f "$DIR_LIBS/std.lib.sh" ]; then
  source "$DIR_LIBS/ansicolors.lib.sh"
  source "$DIR_LIBS/std.lib.sh"
else
  logger -s "[$MODULE_NAME] [ERROR] Impossible de charger la librairie de $MODULE_NAME depuis « $DIR_LIBS ». Fin."
  exit 1
fi

if [ -f "$DIR_CONF/inist.conf.sh" ]; then
  source "$DIR_CONF/inist.conf.sh"
else
  logger -s "[$MODULE_NAME] [ERROR] Impossible de charger la configuration de $MODULE_NAME depuis « $DIR_LIBS ». Fin."
  exit 1
fi

#-----------------------------------------------------------------------
# Vérification des dépendances
#-----------------------------------------------------------------------
if ! IT_CHECK_COMMAND "find" ; then
  IT_MESSAGE "ERROR" "« find » non trouvé, veuillez l'installer avant de continuer."
  exit 1
fi

#-----------------------------------------------------------------------
# Affichage logo CNRS
#-----------------------------------------------------------------------

#-----------------------------------------------------------------------
# Gestion des arguments 
#-----------------------------------------------------------------------
COMMAND="$1"

# Aucun argument : affichage de l'aide
if [ "$#" -lt 1 ]; then
  IT_GREETING
  IT_MESSAGE "WARNING" "Nombre d'argument incorrect !"
  IT_SHOW_HELP
  exit 0
fi

#-----------------------------------------------------------------------
# COMMANDE [+option[s]]
#-----------------------------------------------------------------------

# On est poli, on dit bonjour...
IT_GREETING

# ...et on traite la commande
case $COMMAND in

  #---------------------------------------------------------------------
  # COMMANDE : info
  #---------------------------------------------------------------------
  info )
    "$DIR_TOOLS/inist_info.sh"
    exit 0
  ;;

  #---------------------------------------------------------------------
  # COMMANDE : proxy
  #---------------------------------------------------------------------
  proxy )
    # On charge la lib "network"
    source "$DIR_LIBS/network.lib.sh"
    
    if [ $2 = "on" ]; then
      _it_network_inistProxySet
    elif [ $2 = "off" ]; then
      _it_network_inistProxyUnset
    else
      _it_network_inistProxySet
    fi
    exit 0
  ;;

  #---------------------------------------------------------------------
  # COMMANDE : proxy-chrome
  #---------------------------------------------------------------------
  proxy-chrome )
    "$DIR_TOOLS/inist_proxy_chrome.sh"
    exit 0
  ;;

  #---------------------------------------------------------------------
  # COMMANDE : proxy-firefox
  #---------------------------------------------------------------------
  proxy-firefox )
    "$DIR_TOOLS/inist_proxy_firefox.sh"
    exit 0
  ;;

  #---------------------------------------------------------------------
  # OPTION : --version
  #---------------------------------------------------------------------
  --version | -v )
    cat "$DIR_LIBS/gfx/cnrs.ansi"
    IT_SHOW_VERSION
    exit 0
  ;;

  #---------------------------------------------------------------------
  # Options non gérées...
  #---------------------------------------------------------------------

  * )
    IT_SHOW_HELP
  ;;
  
esac

#-----------------------------------------------------------------------
# FIN PROPRE
#-----------------------------------------------------------------------
exit 0
