#!/usr/bin/env bash
################################################################################
#
# INIST-TOOLS INSTALLATION : POST-INSTALLATION
#
################################################################################

# ------------------------------------------------------------------------------
# Variables globales
# ------------------------------------------------------------------------------
# USER=$(logname)
USER_LOGIN=$(who am i | awk '{print $1}' | head -1)
if [ -z "$USER_LOGIN" ]; then
  USER_LOGIN=$(echo $USER);
fi
ID=$(which id)
USER_GROUP=$($ID -g -n "$USER_LOGIN")

# ------------------------------------------------------------------------------
# Protection des fichiers /etc/sudoers.d/*
# ------------------------------------------------------------------------------
chmod 600 /etc/sudoers.d/inist-tools

# ------------------------------------------------------------------------------
# Répêrtoire de stockage de l'environnement d'execution d'inist-tools
# ------------------------------------------------------------------------------
DIR_ENV="/opt/inist-tools/env"
DIR_CONF="/opt/inist-tools/conf"
if [ ! -d "$DIR_ENV" ]; then
   mkdir -p "$DIR_ENV"
fi
if [ "$USER_LOGIN" != "root" ]; then
  chown -R "$USER_LOGIN":"$USER_GROUP" "$DIR_ENV"
  chown -R "$USER_LOGIN":"$USER_GROUP" "$DIR_CONF"
fi
chmod -R 777 "$DIR_ENV"

# ------------------------------------------------------------------------------
# FIN !
# ------------------------------------------------------------------------------
# exit 0
