#!/usr/bin/env bash
################################################################################
#
# INIST-TOOLS INSTALLATION : POST-DÉSINSTALLATION
#
################################################################################


# ------------------------------------------------------------------------------
# Variables globales
# ------------------------------------------------------------------------------
# Désactivé le 27/10/2016 suite à un bug-report.
# Inutilisé pour l'instant. Devra être remplacé si son utilisation se justifie
# dans le futur.
# Note : <logname> ne renvoit rien dans les terminaux des environnements
#        graphiques (konsole, terminator, xterm) d'une Ubuntu 16.04 (bug
#        connu).
# USER=$(logname)

# ------------------------------------------------------------------------------
# On redevient le user courant
# ------------------------------------------------------------------------------
# su "$USER"

# ------------------------------------------------------------------------------
# Suppression de l'intégration dans le .bashrc
# ------------------------------------------------------------------------------
# grep -vi "# inist-tools" "$HOME/.bashrc" > /run/shm/bashrc.tmp
# mv /run/shm/bashrc.tmp "$HOME/.bashrc"
