#!/usr/bin/env bash
################################################################################
#
# INIST-TOOLS INSTALLATION : POST-INSTALLATION
#
################################################################################

# ------------------------------------------------------------------------------
# Variables globales
# ------------------------------------------------------------------------------
# USER=$(logname)
USER_LOGIN=$(who am i | awk '{print $1}' | head -1)
if [ -z "$USER_LOGIN" ]; then
  USER_LOGIN=$(echo $USER);
fi
ID=$(which id)
USER_GROUP=$($ID -g -n "$USER_LOGIN")

# ------------------------------------------------------------------------------
# Installation des dépendances
# ------------------------------------------------------------------------------
/opt/inist-tools/inistexec apt on
apt-get install -y make ntpdate parallel jq sudo libnotify-bin

# ------------------------------------------------------------------------------
# Protection des fichiers /etc/sudoers.d/*
# ------------------------------------------------------------------------------
chmod 600 /etc/sudoers.d/inist-tools

# ------------------------------------------------------------------------------
# Répêrtoire de stockage de l'environnement d'execution d'inist-tools
# ------------------------------------------------------------------------------
ENV_DIR="/opt/inist-tools/env"
if [ ! -d "$ENV_DIR" ]; then
   mkdir -p "$ENV_DIR"
fi
if [ "$USER_LOGIN" != "root" ]; then
  chown -R "$USER_LOGIN":"$USER_GROUP" "$ENV_DIR"
fi
chmod -R 777 "$ENV_DIR"

# ------------------------------------------------------------------------------
# FIN !
# ------------------------------------------------------------------------------
# exit 0
